import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/app/uiLayout/Footer";
import HomeNav from "./uiLayout/HomeNav";
import Navbar from "./uiLayout/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased`}
      >
        <div className="flex-1 min-h-screen w-full">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
